ARG RUBY_VERSION=3.4.3
FROM docker.io/library/ruby:${RUBY_VERSION}-slim

WORKDIR /rails

RUN apt-get update -qq \
  && apt-get install --no-install-recommends -y \
     curl libvips postgresql-client \
     build-essential git libpq-dev libyaml-dev pkg-config \
  && rm -rf /var/lib/apt/lists /var/cache/apt/archives

ENV RAILS_ENV="development" \
    BUNDLE_PATH="/usr/local/bundle"

RUN gem install bundler -v 2.6.9

EXPOSE 3000
